version: '3'

services:

  flaskapp_new:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: urself
    container_name: flaskapp_new
    tty: true
    command: >
      sh -c "
        flask run -h 0.0.0.0 -p 5000
      "
    restart: always
    ports:
      - "5000:5000"

